Pip removal
ome/ansible-role-omero-python-deps pull request #2
Opened 2017-02-03 13:27 UTC by jburel

Remove the "pypi" option

2017-02-03 13:55 UTC, manics requested changes
How does everyone feel about just making all these Python deps compulsory instead of optional?

2017-02-03 13:55 UTC, manics commented on README.md
> +OMERO depends on several Python modules, they should be installted from distribution packages.
typo: `installted`

2017-02-03 13:55 UTC, manics commented on tasks/main.yml
> +    - python-yaml
The real name of the RPM package is `PyYAML`, `python-yaml` is effectively an alias.

2017-02-03 13:55 UTC, manics commented on tasks/main.yml
> +    - python-pillow
alphabetical order 😄

2017-02-03 13:55 UTC, jburel commented on tasks/main.yml
> +    - python-pillow
:-)

2017-02-03 13:59 UTC, jburel commented
ok for me to have same compulsory since you won't be able to do much if anything w/o them

2017-02-03 14:41 UTC, jburel commented on tasks/main.yml
> +    - python-yaml
read better with alias, happy to roll back

2017-03-09 15:58 UTC, manics requested changes
Apart from the minor comment this looks good, I've tested this by modifying https://github.com/openmicroscopy/ansible-role-omero-server/blob/master/tests/requirements.yml and running `molecule`

2017-03-09 15:58 UTC, manics commented on defaults/main.yml
> -omero_python_deps_recommended: True
You might as well `git rm defaults/main.yml` since there's nothing in it.

2017-03-09 17:28 UTC, jburel commented
@manics done

2017-03-10 10:02 UTC, manics commented
I've retested as before, good to merge.

2017-03-10 15:55 UTC, joshmoore commented
Proposed version for release?

2017-03-10 17:54 UTC, manics commented
How about 1.1 since pypi was effectively a development feature.

2017-03-13 09:04 UTC, joshmoore commented
😼

2017-03-13 09:04 UTC, merged